# Generated by Django 5.0.7 on 2025-03-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.BooleanField(default=True, verbose_name='موجودی'),
        ),
    ]
