# Generated by Django 5.0.7 on 2025-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False, verbose_name='تخفیف خورده'),
        ),
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
    ]
