# Generated by Django 5.0.7 on 2025-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productcategories_product_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='perc_off',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
