# Generated by Django 5.0.7 on 2025-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_product_perc_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='موبایله؟'),
        ),
    ]
