# Generated by Django 5.0.7 on 2025-03-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_product_is_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت های موبایل',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.mobilecompany', verbose_name='شرکت موبایل'),
        ),
    ]
