# Generated by Django 5.0.7 on 2025-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_attachments_product_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='url_address',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AddField(
            model_name='mobilecompany',
            name='url_address',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
