# Generated by Django 5.0.7 on 2025-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_productcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
