# Generated by Django 5.0.7 on 2025-04-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_mobilecompany_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('code', models.CharField(max_length=100, verbose_name='کد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ های محصول',
            },
        ),
    ]
