# Generated by Django 5.0.7 on 2025-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
