# Generated by Django 5.0.7 on 2025-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_productcolor_code_alter_productcolor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ManyToManyField(related_name='colors', to='product_module.product', verbose_name='محصول'),
        ),
    ]
