# Generated by Django 5.0.7 on 2025-04-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_remove_orderdetail_product_color'),
        ('product_module', '0018_productcolors_product_product_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
