# Generated by Django 5.0.7 on 2025-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_delete_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
