# Generated by Django 5.0.7 on 2025-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_remove_product_product_color_delete_productcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='', max_length=200, verbose_name='رنگ های موجود'),
        ),
    ]
