# Generated by Django 5.2.3 on 2025-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار حافظه'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار رام'),
        ),
    ]
