# Generated by Django 5.0.7 on 2025-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
