# Generated by Django 5.0.7 on 2025-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_order_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
