# Generated by Django 5.0.7 on 2025-04-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_alter_orderdetail_final_price'),
        ('product_module', '0015_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcolor'),
        ),
    ]
