# Generated by Django 5.0.7 on 2025-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_orderdetail_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(default='دلخواه', max_length=100, verbose_name='رنگ کالا'),
        ),
    ]
