# Generated by Django 5.0.7 on 2025-04-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_orderdetail_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_color',
        ),
    ]
