# Generated by Django 5.0.7 on 2025-03-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home_sliders')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'اسلایدر تصاویر خانه',
            },
        ),
    ]
