# Generated by Django 5.0.7 on 2025-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='images/home_sliders', verbose_name='تصویر'),
        ),
    ]
