# Generated by Django 5.0.7 on 2025-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='اسم سایت')),
                ('pic_1', models.ImageField(upload_to='images/info', verbose_name='تصویر یک')),
                ('pic_2', models.ImageField(upload_to='images/info', verbose_name='تصویر دو')),
                ('description_1', models.TextField(verbose_name='توضیحات اول')),
                ('title_2', models.CharField(max_length=100, verbose_name='عنوان دوم')),
                ('description_2', models.TextField(verbose_name='توضیحات دوم')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
