# Generated by Django 5.0.7 on 2025-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.TextField(default='', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='info',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/info', verbose_name='لوگو'),
        ),
    ]
