# Generated by Django 5.0.7 on 2025-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0004_info_work_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='copy_right',
            field=models.CharField(default='', max_length=100, verbose_name='متن کپی رایت'),
        ),
    ]
