# Generated by Django 5.0.7 on 2025-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(default='', verbose_name='درباره شخص'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='', verbose_name='آدرس شخص'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_avatar', verbose_name='تصویر پروفایل'),
        ),
    ]
